apiVersion: skaffold/v2beta28
kind: Config
build:
  artifacts:
    - image: arthurgurbanov177/prescaling-exporter
      ko: {}
deploy:
  helm:
    releases:
      - name: prescaling-exporter
        chartPath: helm/prescaling-exporter
        namespace: prescaling-exporter
        createNamespace: true
        artifactOverrides:
          image: arthurgurbanov177/prescaling-exporter
        imageStrategy:
          helm: {}
